### ISSUE TITLE
Empty finally block

### ISSUE THREAD

**Issue by SemenMartynov** [Gradergage/JsonValidator#1]
Maybe you want to free some resources here?))

https://github.com/Gradergage/JsonValidator/blob/eafaeea824ee567171210f10e55164bbb8bc62a0/src/main/java/Validator.java#L52

**Comment by SemenMartynov** [comment]
??

Use feature-branches for close issues.

**Comment by SemenMartynov** [comment]
Waiting for news here...

**Comment by Gradergage** [comment]
https://github.com/Gradergage/JsonValidator/commit/55898ecf152be889145ef3a8e30031537ed5e733
https://github.com/Gradergage/JsonValidator/blob/55898ecf152be889145ef3a8e30031537ed5e733/src/main/java/Validator.java#L58

**Comment by SemenMartynov** [comment]
I think your `requestId` will allays be 0. Can you check it?

**Comment by SemenMartynov** [comment]
Any updates here?
