### ISSUE TITLE
Format your description

### ISSUE THREAD

**Issue by SemenMartynov** [Gradergage/JsonValidator#3]
Markdown contains code highlighting tools

https://guides.github.com/features/mastering-markdown/

This is for your README.md file.

**Comment by Gradergage** [comment]
**Completed**, *description* and *code* have been styled

**Comment by SemenMartynov** [comment]
Do not edit files in the web-interface.
You have to use feature-branch for each issue and link commit with issue via comment.

**Comment by SemenMartynov** [comment]
Now there is nothing to do in this task. I just give a general recommendation.

**Comment by SemenMartynov** [comment]
Oh, `github.com/username/projectname` -- username??

**Comment by Gradergage** [comment]
[https://github.com/Gradergage/JsonValidator/commit/97e64a81e34a5f937a0a94aa1b2a41cb2aea6216](url)

**Comment by Gradergage** [comment]
https://github.com/Gradergage/JsonValidator/commit/97e64a81e34a5f937a0a94aa1b2a41cb2aea6216 Actually, I dont undestand you. I have some commits, but i can only drop the link here, there are no some special instruments to link commit

**Comment by SemenMartynov** [comment]
1. For each issue you create a new feature-branch (`feature/original-issue-name`)
2. Then you make a fix and note git issue if in commit message while committing
3. And merge you feature branch into the main one

https://help.github.com/articles/autolinked-references-and-urls/
https://help.github.com/articles/closing-issues-using-keywords/
