### ISSUE TITLE
Fix error message

### ISSUE THREAD

**Issue by SemenMartynov** [Gradergage/JsonValidator#4]
In case of incorrect JSON I receive this file, instead of filename.

**Comment by Gradergage** [comment]
https://github.com/Gradergage/JsonValidator/commit/55898ecf152be889145ef3a8e30031537ed5e733
https://github.com/Gradergage/JsonValidator/blob/55898ecf152be889145ef3a8e30031537ed5e733/src/main/java/Validator.java#L39

**Comment by SemenMartynov** [comment]
`"request_id": 0`
Counter doesn't work,
